FROM python:3.12-slim

# Empêche la mise en cache et force l'affichage des logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# AJOUTE CECI : Assure que les exécutables pip (comme celery) sont trouvables
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
# Utilise --user ou assure-toi d'installer globalement
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --force-reinstall bcrypt==4.0.1

COPY . .
