FROM python:3.12-slim

WORKDIR /app

# Dépendances système pour compiler bcrypt et sqlite
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install bcrypt==4.0.1 

COPY . .

EXPOSE 8000

CMD ["python", "-m", "backend.api.main"]
